export const partidaVivo = {
  name: "Partida en VIVO",
  elementList: [
    {
      id: "149",
      visible: true,
      type: "image",
      x: 0,
      y: 0,
      name: "vantage 2",
      url: "https://cf.geekdo-images.com/IqjgReQA-wg3BI8WtrFK6A__original/img/LpFQZKoPkUaoN_nJbtE2hBhj_0w=/0x0/filters:format(jpeg)/pic8550889.jpg",
      scale: 1,
      opacity: 1,
    },
    {
      id: "150",
      visible: true,
      type: "circle",
      x: 300,
      y: 300,
      color: "#0000FF",
      borderColor: "#FFFFFF",
      borderWidth: 3,
      radius: 80,
      opacity: 1,
      shadow: "",
    },
    {
      id: "151",
      visible: true,
      type: "polygon",
      x: 700,
      y: 300,
      sides: 6,
      size: 140,
      color: "#CC0022",
      borderColor: "#FFFFFF",
      borderWidth: 6,
      rotation: 20,
      opacity: 1,
      shadow: "",
    },
  ],
};
