export const ruedaLudica = {
  name: "Rueda Lúdica",
  elementList: [
    {
      id: "145",
      visible: true,
      type: "text",
      text: "Pablito clabo Lorem ipsum.",
      x: 10,
      y: 10,
      width: 1500,
      color: "#FFFF00",
      fontSize: 90,
      lineHeight: 1.4,
      fontFamily: "Arial",
      bold: 400,
      italic: true,
      textAlign: "left",
      uppercase: false,
      shadow: "0px 10px 1px #FFF",
    },
    {
      id: "146",
      visible: true,
      type: "text",
      text: "Otro texto",
      x: 60,
      y: 220,
      width: 1500,
      color: "#FFFFFF",
      fontSize: 70,
      lineHeight: 1.4,
      fontFamily: "Verdana",
      bold: 400,
      italic: false,
      textAlign: "left",
      uppercase: false,
      shadow: "",
    },
  ],
};
